- hosts: local
  become: yes
  tasks:
   - name: Add an apt signing key for Docker
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Add apt repository for stable version
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

   - name: Install docker and its dependecies
     apt: 
      name: ["docker-ce","docker-ce-cli","containerd.io"]
      state: present
      update_cache: yes

   - name: start Docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: Add an apt signing key for Kubernetes
     apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

   - name: Adding apt repository for Kubernetes
     apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
   
   - name: install kubelet
     apt:
        name: kubelet
        state: present
        update_cache: true

   - name: install kubeadm
     apt:
        name: kubeadm
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

   - name: install kubectl
     apt:
        name: kubectl
        state: present

