- hosts: all
  become: yes
  tasks:
    - name: Creating Namespace and Service Account for Ingress Controller
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/common/ns-and-sa.yaml
    
    - name: Creating Secret for TLS certificate and key for default server in nginx
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/common/default-server-secret.yaml
    
    - name: Creating a config map for nginx configuration
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/common/nginx-config.yaml

    - name: Creating Resource Definitions (Optional)
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/common/custom-resource-definitions.yaml

    - name: Creating Cluster role and binding it to the service account
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/rbac/rbac.yaml

    - name: Deploying Ingress Controller
      command: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/master/deployments/daemon-set/nginx-ingress.yaml
